Vscode publish (#2838)
Extension
https://marketplace.visualstudio.com/items?itemName=typespec.typespec-vscode

diff --git a/eng/pipelines/ci.yml b/eng/pipelines/ci.yml
--- a/eng/pipelines/ci.yml
+++ b/eng/pipelines/ci.yml
@@ -22,8 +22,6 @@ jobs:
 
     steps:
       - template: ./templates/install.yml
-        parameters:
-          nodeVersion: "20.x"
       - template: ./templates/build.yml
 
       - script: pnpm run test-official
@@ -35,6 +33,23 @@ jobs:
           pnpm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
           pnpm -r publish --access public --no-git-checks
         displayName: Publish packages
+
+      - script: pnpm run pack:all
+        displayName: Pack packages
+
+      - publish: $(Build.SourcesDirectory)/temp/artifacts
+        artifact: packages
+        displayName: Publish packages(.tgz) as pipeline artifacts
+
+      - task: CopyFiles@2
+        inputs:
+          SourceFolder: "$(Build.SourcesDirectory)/packages/typespec-vscode"
+          Contents: "*.vsix"
+          TargetFolder: "$(Build.ArtifactStagingDirectory)/vscode-extension"
+
+      - publish: $(Build.ArtifactStagingDirectory)/vscode-extension
+        artifact: vscode-extension
+        displayName: Publish VSCode extension(.vsix) as pipeline artifacts
 
       - task: AzureCLI@1
         displayName: "Publish bundled packages to package storage"
@@ -56,6 +71,35 @@ jobs:
               --source "./packages/playground-website/dist/" ^
               --overwrite
 
+  - job: publish_vscode
+    displayName: Publish VSCode extension
+    dependsOn: npm_stable
+    pool:
+      name: azsdk-pool-mms-ubuntu-2004-general
+      vmImage: ubuntu-20.04
+
+    steps:
+      - download: current
+        artifact: vscode-extension
+        displayName: Download VSCode extension(.vsix) from pipeline artifacts
+
+      - script: |
+          vsix="$(find $(Pipeline.Workspace)/vscode-extension -type f -iname "typespec-vscode-*.vsix" )"
+
+          [ -z "$vsix" ] && echo "Error: Couldn't find vsix" && exit 1
+
+          echo "Found core package $vsix"
+          echo "Found modelerfour package $modelerfourPkg"
+        displayName: Find packages path
+
+      - template: ./templates/install.yml
+
+      - script: npm run deploy -- --skip-duplicate --packagePath $(Pipeline.Workspace)/vscode-extension/typespec-vscode-*.vsix
+        displayName: Publish
+        workingDirectory: packages/typespec-vscode
+        env:
+          VSCE_PAT: $(azuresdk-devdiv-openapi-extension-marketplace-devops-pat)
+
   - job: npm_dev
     dependsOn: npm_stable
     displayName: Npm publish dev version
@@ -68,8 +112,6 @@ jobs:
 
     steps:
       - template: ./templates/install.yml
-        parameters:
-          nodeVersion: "20.x"
       - template: ./templates/build.yml
 
       - script: node ./packages/internal-build-utils/cmd/cli.js bump-version-preview .
